[package]
name = "fractal-rs-2"
version = "0.1.0"
authors = ["Kneelawk <kneelawk@gmail.com>"]
edition = "2018"
resolver = "2"

[dependencies]
anyhow = "^1.0.43"
async-trait = "^0.1.51"
bytemuck = "^1.7.2"
chrono = "^0.4.19"
cgmath = "^0.18.0"
futures = "^0.3.12"
imgui = "^0.8.0"
imgui-wgpu = "^0.17.0"
imgui-winit-support = "^0.8.0"
lazy_static = "^1.4.0"
log = "^0.4.14"
log4rs = "^1.0.0"
mtpng = "^0.3.5"
naga = { git = "https://github.com/gfx-rs/naga.git", branch = "master", features = ["wgsl-in", "wgsl-out"] }
num-complex = "^0.3.1"
num_cpus = "^1.13.0"
num-traits = "^0.2.14"
#png = "^0.16.1"
rayon = "^1.5.0"
regex = "^1.4.3"
serde = "^1.0.127"
thiserror = "^1.0.26"
tokio = { version = "^1.2.0", features = ["fs", "io-util", "macros", "rt", "rt-multi-thread", "sync"] }
tokio-stream = { version = "^0.1.7", features = ["sync"] }
winit = "^0.25.0"
wgpu = "^0.10.2"
