[package]
name = "fractal-rs-2"
version = "0.1.0"
authors = ["Kneelawk <kneelawk@gmail.com>"]
edition = "2018"

[dependencies]
futures = "^0.3.12"
lazy_static = "^1.4.0"
num-complex = "^0.3.1"
num_cpus = "^1.13.0"
png = "^0.16.1"
rayon = "^1.5.0"
regex = "^1.4.3"
tokio = { version = "^1.2.0", features = ["rt-multi-thread", "macros", "sync"] }
