[package]
name = "fractal-viewer-rs"
version = "0.1.0"
authors = ["Kneelawk <kneelawk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "^0.12.4"
lazy_static = "^1.4.0"
num-complex = "^0.2.4"
num_cpus = "^1.12.0"
png = "^0.16.1"
regex = "^1.3.4"
serde = "^1.0.126"
serde_derive = "^1.0.126"
toml = "^0.5.8"

[dependencies.clap]
version = "^2.33.3"
features = ["yaml"]
