[package]
name = "fractal-rs-2"
version = "0.1.0"
authors = ["Kneelawk <kneelawk@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "^1.0.43"
chrono = "^0.4.19"
error-chain = "^0.12.4"
futures = "^0.3.12"
lazy_static = "^1.4.0"
log4rs = "^1.0.0"
num-complex = "^0.3.1"
num_cpus = "^1.13.0"
num-traits = "^0.2.14"
png = "^0.16.1"
rayon = "^1.5.0"
regex = "^1.4.3"
serde = "^1.0.127"
tokio = { version = "^1.2.0", features = ["rt-multi-thread", "macros", "sync"] }
