[package]
name = "fractal-rs-2"
version = "0.1.0"
authors = ["Kneelawk <kneelawk@gmail.com>"]
edition = "2018"

[dependencies]
futures = "^0.3.12"
tokio = { version = "^1.2.0", features = ["rt-multi-thread", "macros", "sync", "signal"] }
rayon = "^1.5.0"
