format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
merge_imports = true
wrap_comments = true
