//! This crate is the primary API that various fractal generator backends will implement.

pub mod args;
pub mod target;
pub mod util;
pub mod view;

/// Anyhow is used by this API.
pub use anyhow;
/// Rug multi-precision complex numbers are used by this API.
pub use rug;
/// Streaming iterators are used by this API.
pub use streaming_iterator;

use crate::args::{Multisampling, Smoothing};
use crate::target::GeneratorTargetSet;
use crate::view::View;
use futures_core::future::BoxFuture;
use rug::Complex;
use serde::{Deserialize, Serialize};
use std::fmt::{Debug, Formatter};

/// Represents a set of options passed to a fractal generator at initialization.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FractalOpts {
    pub mandelbrot: bool,
    pub iterations: u32,
    pub smoothing: Smoothing,
    pub multisampling: Multisampling,
    pub c: Complex,
    pub radius_squared: f32,
}

/// Represents a block of pixels, likely generated by a fractal generator.
#[derive(Clone)]
pub struct PixelBlock {
    pub view: View,
    pub image: Box<[u8]>,
}

// Special debug that doesn't look as ugly
impl Debug for PixelBlock {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PixelBlock")
            .field("view", &self.view)
            .field("image", &format!("[{} bytes]", self.image.len()))
            .finish()
    }
}

/// Structs implementing this trait can be used to create [`ConfiguredGenerator`]s.
///
/// Structs implementing this trait generally describe the general structure of
/// a fractal generator, independent of any information about the fractal being
/// generated. Is the generator run on the CPU or GPU, over a network, or some
/// combination?
pub trait FractalGenerator {
    fn create_instance(
        &self,
        opts: FractalOpts,
    ) -> BoxFuture<'static, anyhow::Result<Box<dyn ConfiguredGenerator + Send + 'static>>>;
}

/// Structs implementing this trait can be used to generate fractals.
///
/// Note that all these methods return futures because they may require
/// communication over a network.
/// Also note that these futures have a `'static` lifetime, meaning they can be
/// held and polled separately from the `GeneratorInstance` itself.
pub trait ConfiguredGenerator {
    /// Gets the recommended minimum number of views that should be submitted to
    /// this generator together as a single batch in order to operate
    /// efficiently.
    fn min_views_hint(&self) -> BoxFuture<'static, anyhow::Result<usize>>;

    /// Starts the generation of a fractal.
    fn start_generation(
        &self,
        views: &[View],
        target: &GeneratorTargetSet,
    ) -> BoxFuture<'static, anyhow::Result<Box<dyn RunningGenerator + Send + 'static>>>;
}

/// Represents a running fractal generator.
pub trait RunningGenerator {
    /// Cancels this generator instance.
    fn cancel(&self);

    /// Gets this generator instance's current progress.
    fn progress(&self) -> BoxFuture<'static, anyhow::Result<f32>>;

    /// Checks whether this fractal generator instance is still running.
    fn running(&self) -> BoxFuture<'static, anyhow::Result<bool>>;
}
