[package]
name = "fractal-rs-3-lang"
version = "0.1.0"
edition = "2024"

[dependencies]
fractal-rs-3-utils.workspace = true

ariadne.workspace = true
chumsky.workspace = true
fhex.workspace = true
rug.workspace = true
serde.workspace = true

[dev-dependencies]
parameterized.workspace = true
pretty_assertions.workspace = true
