# This handles the building and publishing of the project's release artifacts

name: release-linux
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag version
        uses: dawidd6/action-get-tag@v1
        id: tag_version
      - name: Install Linux dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-11-26
      - name: Install cargo-deb
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deb
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: deb
      - name: Create 'dist' directory
        run: mkdir dist
      - name: Copy release files
        run: cp target/release/fractal-rs-2 dist/
      - name: Archive release
        uses: thedoctor0/zip-release@master
        with:
          type: 'tar'
          directory: 'dist/'
          filename: fractal-rs-2_${{ steps.tag_version.outputs.tag }}+${{ env.GITHUB_RUN_NUMBER }}_x86_64-linux-vulkan.tgz
          path: 'fractal-rs-2*'
      - name: Copy DEB to dist
        run: cp target/debian/fractal-rs-2*.deb dist/fractal-rs-2_${{ steps.tag_version.outputs.tag }}+${{ env.GITHUB_RUN_NUMBER }}_x86_64-linux-vulkan.deb
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          body_path: changelogs/changelog-${{ steps.tag_version.outputs.tag }}.md
          files: |
            dist/fractal-rs-2_${{ steps.tag_version.outputs.tag }}+${{ env.GITHUB_RUN_NUMBER }}_x86_64-linux-vulkan.tgz
            dist/fractal-rs-2_${{ steps.tag_version.outputs.tag }}+${{ env.GITHUB_RUN_NUMBER }}_x86_64-linux-vulkan.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
